### ISSUE TITLE
Крутая идея. Развивайте библиотеку дальше.

### ISSUE THREAD

**Issue by megafetis** [TheDusty01/BlazingState#1]
Я пытался сделать свой менеджер по управлению состоянием на основе `System.Reflection.DispatchProxy`. Это была плохая идея, так-как лучше создавать много небольших объектов `State` а не контролировать изменение отдельных свойств.
Sorry, i dont know english well

**Comment by TheDusty01** [comment]
Please use some translator or ChatGPT to translate :)
