### ISSUE TITLE
Make TState type nullable by demand, not always

### ISSUE THREAD

**Issue by megafetis** [TheDusty01/BlazingState#2]
nullable state
```
IStateobserver<MyNullableState?> state1 = new();
```

not nullable state
```
IStateObserver<MyNotNullableState> state1 = new(new MyNotNullableState() );
```

**Comment by TheDusty01** [comment]
You are welcome to create a PR :) I'd suggest you to use Root Level Cascading Values though: https://learn.microsoft.com/en-us/aspnet/core/blazor/components/cascading-values-and-parameters?view=aspnetcore-8.0#root-level-cascading-values

**Comment by megafetis** [comment]
Hello! Can you approve this PR? Can you explain if not. My project is depends of your decision

**Comment by TheDusty01** [comment]
Merged & published, thanks for your contibution!

**Comment by megafetis** [comment]
Thanks! cool!
